# Project name that appears next to the logo.
projectName: Nice Docs
projectLogo: "book.svg"

# Links for the navbar
navigation:
  - caption: Site
    icon: "fas fa-globe"
    url: "https://aboni.dev/"
  - caption: Github
    icon: "fab fa-github"
    url: "https://github.com/ajboni/"

# Copyright Disclaimer on Footer
copyright: Made with 🧉 by Alexis Boni. Licensed under the GPLv3 License.
