# Project and logo on the navbar.
projectName: Nice Docs
projectLogo: "book.svg"

# Index document to load when the usear reach root URL. Should be the same for every language.
indexDocument: ".index"

# Default language for the site, used when user reach root URL without /lang/ slug.  
# Must be the same name as the root folder of docs.
defaultLanguage: "eng"

# Available Languages 
availableLanguages:
  - id: eng
    icon: "fa fa-user"
    caption: "English"
  - id: spa
    icon: "fa fa-user"
    caption: "Español"
  - id: zzz
    icon: "fa fa-user"
    caption: "ZZZ"

# Links for the navbar
navigation:
  - caption: Site
    icon: "fas fa-globe"
    url: "https://aboni.dev/"
  - caption: Github
    icon: "fab fa-github"
    url: "https://github.com/ajboni/"

# Copyright Disclaimer on Footer
copyright: Made with 🧉 by <a href="https://aboni.dev">Alexis Boni</a>. Licensed under the GPLv3 License.
