projectName: Project Name
navigation:
  - caption: Site
    url: "https://aboni.dev/"
  - caption: Github
	 url: "https://github.com/ajboni/"
copyright: Made with 🧉 by Alexis Boni. Licensed under the GPLv3 License.